version: '3.8'

services:
  web:
    container_name: gunicorn_django
    build:
      context: .
    volumes:
      - static:/app/static/
      - media:/app/media/
    expose:
      - 8001
    env_file:
      - .env.prod
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/app/static/
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7-alpine
    expose:
      - 6379
volumes:
  learn_django_postgres_data:
    external: true
  static:
  media: