# Generated by Django 4.0.3 on 2022-05-08 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_url_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 5, 8), verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
