# Generated by Django 4.0.3 on 2023-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_reviews_email_remove_reviews_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('NOT RATED', 'NOT RATED'), ('UNRATED', 'UNRATED')], default='NOT RATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
