# Generated by Django 4.0.3 on 2023-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_mpaa_rating_alter_reviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('NOT RATED', 'NOT RATED'), ('UNRATED', 'UNRATED')], default='NOT RATED', max_length=10, verbose_name='MPAA'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Постер'),
        ),
    ]
